name: Release

on:
  push:
    branches:
      - "master"

jobs:
  release:
    env:
      CTN1: ghcr.io/i13302/pandoc:latest
      CTN2: ghcr.io/i13302/printout:latest
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy base dir to pdf dir
        run: make -f .tools/Makefile base

      - name: Convert file markdown to pdf
        run: make -f .tools/Makefile CTN1=${{ env.CTN1 }} CTN2=${{ env.CTN2 }} run

      - name: check Convert
        run: make -f .tools/Makefile check

      - name: Add executed
        run: chmod +x ./.github/scripts/paper_release.sh

      - name: Release
        env:
          PDFDIR: work/pdf
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/scripts/paper_release.sh
