name: Release

on:
  push:
    branches:
      - "master"

jobs:
  release:
    env:
      CTN1: ghcr.io/i13302/pandoc:latest
      CTN2: ghcr.io/i13302/printout:latest
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull Image
        run: |
          docker pull ${{ env.CTN1 }}
          docker pull ${{ env.CTN2 }}

      - name: Copy base dir to pdf dir
        run: make -f .tools/Makefile base

      - name: Convert file markdown to pdf
        run: make -f .tools/Makefile CTN1=${{ env.CTN1 }} CTN2=${{ env.CTN2 }} run

      - name: Check Convert
        run: make -f .tools/Makefile check

      - name: Set BRANCH
        run: echo "${GITHUB_REF#refs/heads/}" | sed -e 's/\//_/g' -e 's/^/BRANCH=/g' >> $GITHUB_ENV

      - name: Set DATE
        run: echo "DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV

      - name: Upload file pdf.
        uses: actions/upload-artifact@master
        with:
          name: PDFDIR-${{ env.DATE }}-${{ env.BRANCH }}
          path: work/pdf/*.pdf

      - name: Add executed
        run: chmod +x ./.github/scripts/paper_release.sh

      - name: Release
        env:
          PDFDIR: work/pdf
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/scripts/paper_release.sh
