name: "master push"

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: chackout
        uses: actions/checkout@v2

      - name: Convert file markdown to pdf
        run: |
          make CTN2=ghcr.io/i13302/printout run

      - name: Add executed
        run: chmod +x ./.github/scripts/paper_release.sh

      - name: Release
        env:
          PDFDIR: work/pdf
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/scripts/paper_release.sh
