name: upload_file

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  upload_file:
    runs-on: ubuntu-20.04
    steps:
      - name: chackout
        uses: actions/checkout@v2

      - name: Convert file markdown to pdf
        run: |
          make CTN2=ghcr.io/i13302/printout run

      - name: Upload file pdf.
        uses: actions/upload-artifact@master
        with:
          name: convert_dir
          path: work/pdf/*.pdf
