name: Upload File

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "!master"

jobs:
  upload_file:
    env:
      CTN1: ghcr.io/i13302/pandoc:latest
      CTN2: ghcr.io/i13302/printout:latest
    runs-on: ubuntu-20.04
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch

      - name: Print branch name
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}

      - name: Set DATE
        run: echo "DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV

      - name: chackout
        uses: actions/checkout@v2

      - name: Pull Image
        run: |
          docker pull ${{ env.CTN1 }}
          docker pull ${{ env.CTN2 }}

      - name: Copy base dir to pdf dir
        run: make -f .tools/Makefile base

      - name: Convert file markdown to pdf
        run: make -f .tools/Makefile CTN1=${{ env.CTN1 }} CTN2=${{ env.CTN2 }} run

      - name: check Convert
        run: make -f .tools/Makefile check

      - name: Upload file pdf.
        uses: actions/upload-artifact@master
        with:
          name: PDFDIR-${{ env.DATE }}-${{ steps.extract_branch.outputs.branch }}
          path: work/pdf/*.pdf
